site_name: Pet Shop Guará
site_url: https://mdsreq-fga-unb.github.io/2024.2-T03-PetShopGuara/
repo_url: "https://github.com/mdsreq-fga-unb/2024.2-T03-PetShopGuara"
theme:
  name: material
  name: material
  palette:
    scheme: 'default + dark'
    primary: 'deep orange'
    accent: 'orange'
  logo: assets/imgs/logo.png
  favicon: assets/imgs/logo.png


nav:
  - Página Inicial: index.md 
  - Cenário atual do cliente e do negócio: CenarioAtual/Cenario.md 
  - Visão do Produto e Projeto: 
    - Solução Proposta : VisãoProduto/Solucao.md
    - Estratégias de Engenharia de Software : VisãoProduto/Estrategias.md
    - Engenharia de Requisitos: VisãoProduto/EngRequisitos.md
    - Cronogramas e Entregas : VisãoProduto/Cronograma.md
    - Interação entre Equipe e Cliente : VisãoProduto/Interação.md
    - Requisitos de Software: VisãoProduto/Requisitos.md
    - DoR e DoD: VisãoProduto/DoRDoD.md
    - Backlog do Produto: VisãoProduto/Backlog.md
  - Lições Aprendidas: 
    - Unidade 1 : Unidades/Unidade1.md
    - Unidade 2 : Unidades/Unidade2.md
  - Estudos de Caso:
    - Product Backlog Building: EstudosDeCaso/PBB.md
    - User Story Mapping: EstudosDeCaso/USM.md
  - Fases do OpenUP:
    - Concepção: FasesOpenUP/Concepcao.md
    - Elaboração: FasesOpenUP/Elaboracao.md
    - Construção: FasesOpenUP/Construcao.md
    - Transição: FasesOpenUP/Transicao.md
  - Apresentações: 
    - Apresentação Unidade 1 : Entregas/Entrega1.md
    - Apresentação Unidade 2 : Entregas/Entrega2.md
  
  
