site_name: Pet Shop Guará
site_url: https://mdsreq-fga-unb.github.io/2024.2-T03-PetShopGuara/
repo_url: "https://github.com/mdsreq-fga-unb/2024.2-T03-PetShopGuara"
theme:
  name: material

nav:
  - Página Inicial: home.md 
  - Cenário atual do ciente e do negócio: CenarioAtual/Cenario.md 
  - Visão do Produto e Projeto: 
    - Solução Proposta : VisãoProduto/Solucao.md
    - Estratégias de Engenharia de Software : VisãoProduto/Estrategias.md
    - Cronogramas e Entregas : VisãoProduto/Cronograma.md
    - Interação entre Equipe e Cliente : VisãoProduto/Interação.md
  - Lições Aprendidas: 
    - Unidade 1 : Unidades/Unidade1.md
  
